### ISSUE TITLE
Exploring Twitter Data with more than one keyword

### ISSUE THREAD

**Issue by neginhayatbini** [cnstlungu/Notebooks#1]
Hey!
I am trying to use the Exploring Twitter Data using Python .ipynb to analyze Twitter data for a few keywords. The notebook is working for one keyword (keywords, language = ['brexit'], 'en'), however, could you let me know how to include more than one keyword for the search? 

Thank you!

**Comment by cnstlungu** [comment]
Hi!

That should be straighforward: just say (keywords, language = ['brexit','economy'], 'en'). The _keywords_ variable should is a list so it can contain multiple terms.

Regards

**Comment by neginhayatbini** [comment]
Thanks for your response! 
I was also wondering for how long the tweets are stored by running this code using the option "recent". Thank you.

**Comment by cnstlungu** [comment]
Hi again @neginhayatbini .
As per the documentation [here](https://developer.twitter.com/en/docs/tweets/search/overview) , the 'recent' option searches against a sampling of recent Tweets published in the past 7 days. 
Regards
