### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Gautamshahi** [cnstlungu/Notebooks#3]
Hello,

I have followed the same steps but getting the TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

How to resolve the issue?

![Screenshot 2020-03-23 at 19 02 53](https://user-images.githubusercontent.com/3966230/77348148-3f40db80-6d39-11ea-9298-3c94e3acb1be.png)

**Comment by cnstlungu** [comment]
Do you have any _None_ coordinates in locations? I would try to get rid of them before trying to append them to the map.

Regards

**Comment by Gautamshahi** [comment]
Thanks, I have modified the code the provide only integer value for the time being. But the radius of getting increased only for a few coordinates. 

I tried all possible way but unable to rectify the issue.
![Screenshot 2020-03-23 at 23 33 39](https://user-images.githubusercontent.com/3966230/77369472-fef45400-6d5e-11ea-90c2-8c32aced1752.png)

**Comment by cnstlungu** [comment]
That would depend on the get_radius helper function we've defined.
If the notebook, I've defined it as below. You obviously tweak it so it makes sense for your numbers. If you've got an unbalanced dataset (so a few locations with big counts), try a function like square root or log to make them all play nicely in a graph.  

```
# helper function
def get_radius(freq):
    if freq < 50:
        return 0.5
    elif freq < 200:
        return 1.2
    elif freq < 1000:
        return 1.8
```

Regards

**Comment by Gautamshahi** [comment]
Yes, I played with Helper function also with unable to get the desired result. If could share any tutorial or official page for helper function then it will be useful like the maximum size of circle allowed etc.

Thank you for your time.

**Comment by cnstlungu** [comment]
You can try and review the [Circle documentation](https://matplotlib.org/api/_as_gen/matplotlib.patches.Circle.html) or look at some [more examples ](https://stackoverflow.com/questions/9215658/plot-a-circle-with-pyplot).
Hope this works out for you :)
